package:
  name: blaze
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  git_url: ../

requirements:
  run:
    - python
    - numpy >=1.7
    - blaze-core
    - h5py
    - cytoolz
    - pandas >=0.15.0
    - pytables >=3.0.0
    - pymongo >=2.8
    - numba
    - bcolz
    - unittest2 [py26]

test:
  requires:
    - pytest >=2.7.0
    - dask
    - dynd-python
    - pytables

  commands:
    - py.test -vx --doctest-modules --doctest-ignore-import-errors --pyargs blaze -rsxX

about:
  home: http://blaze.pydata.org
  license: BSD
