package:
  name: blaze-core
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  entry_points:
    - blaze-server = blaze.server.spider:_main

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - flask >=0.10.1
    - flask-cors
    - odo >=0.4.0
    - psutil
    - sqlalchemy >=0.8.0
    - toolz

  run:
    - python
    - cytoolz
    - dask
    - flask >=0.10.1
    - flask-cors
    - odo >=0.4.0
    - psutil
    - pyyaml
    - requests
    - sqlalchemy >=0.8.0

test:
  requires:
    - pytest >=2.7.0
    - h5py

  commands:
    - py.test -vx --doctest-modules --doctest-ignore-import-errors --pyargs blaze -rsxX

about:
  home: http://blaze.pydata.org
  license: BSD
