package:
    name: blaze
    version: "0.5.1"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}
    script:
      - cd $RECIPE_DIR
      - $PYTHON setup.py install

requirements:
    build:
      - python
      - numpy

    run:
      - python
      - dynd-python
      - numpy
      - multipledispatch
      - sqlalchemy
      - pandas
      - h5py
      - datashape
      - flask
      - requests
      - cytoolz
      - toolz
      - unicodecsv

about:
    home: http://blaze.pydata.org
    license: BSD
