
# /home/stephen/continuum/blazepro/blaze/aterm/ayacc.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xdf\x9bbv\xe6\xc7\xee\x98\xb4\xe6a\xc096\x1cd'
    
_lr_action_items = {'STRING':([0,3,9,22,23,25,26,36,38,],[1,1,1,1,1,1,1,1,1,]),'NAME':([0,3,9,22,23,25,26,36,38,],[12,12,12,12,12,12,12,12,12,]),'INT':([0,3,9,22,23,25,26,36,38,],[13,13,13,13,13,13,13,13,13,]),'DOUBLE':([0,3,9,22,23,25,26,36,38,],[17,17,17,17,17,17,17,17,17,]),'PLACEHOLDER':([5,],[20,]),']':([1,2,4,6,7,8,9,10,11,12,13,15,16,17,19,21,24,25,27,28,33,35,37,42,],[-25,-1,-5,-10,-8,-7,-28,-9,-4,-13,-12,-6,-2,-11,-20,28,-22,-28,-27,-19,-21,-16,-3,-26,]),',':([1,2,3,4,6,7,8,9,10,11,12,13,15,16,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,40,41,42,],[-25,-1,-28,-5,-10,-8,-7,-28,-9,-4,-13,-12,-6,-2,-11,25,-20,25,-28,-28,-22,-28,-28,-27,-19,36,-17,38,-14,25,36,-16,-28,-3,-28,36,38,-26,]),'<':([0,3,9,22,23,25,26,36,38,],[5,5,5,5,5,5,5,5,5,]),')':([1,2,3,4,6,7,8,10,11,12,13,15,16,17,18,19,22,24,25,26,27,28,29,30,33,34,35,36,37,40,42,],[-25,-1,-28,-5,-10,-8,-7,-9,-4,-13,-12,-6,-2,-11,24,-20,-28,-22,-28,-28,-27,-19,35,-17,-21,39,-16,-28,-3,-18,-26,]),'(':([0,3,9,11,12,13,17,20,22,23,25,26,36,38,],[3,3,3,22,-13,-12,-11,26,3,3,3,3,3,3,]),'{':([0,1,3,4,6,7,8,9,10,11,12,13,15,16,17,22,24,25,26,27,28,35,36,42,],[-28,-25,-28,-5,-10,-8,-7,-28,-9,-4,-13,-12,-6,23,-11,-28,-22,-28,-28,-27,-19,-16,-28,-26,]),'>':([20,39,],[27,42,]),'}':([1,4,6,7,8,10,11,12,13,15,17,23,24,27,28,31,32,35,38,41,42,],[-25,-5,-10,-8,-7,-9,-4,-13,-12,-6,-11,-28,-22,-27,-19,37,-14,-16,-28,-15,-26,]),'[':([0,3,9,22,23,25,26,36,38,],[9,9,9,9,9,9,9,9,9,]),'$end':([0,1,2,4,6,7,8,10,11,12,13,14,15,16,17,24,27,28,35,37,42,],[-28,-25,-1,-5,-10,-8,-7,-9,-4,-13,-12,0,-6,-2,-11,-22,-27,-19,-16,-3,-26,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,3,9,22,23,25,26,36,38,],[11,11,11,11,11,11,11,11,11,]),'string':([0,3,9,22,23,25,26,36,38,],[7,7,7,7,7,7,7,7,7,]),'avalue':([0,3,9,22,25,26,36,],[2,2,2,2,2,2,2,]),'tuple':([0,3,9,22,23,25,26,36,38,],[8,8,8,8,8,8,8,8,8,]),'expr':([0,3,9,22,25,26,36,],[14,19,19,30,19,30,30,]),'list':([0,3,9,22,23,25,26,36,38,],[15,15,15,15,15,15,15,15,15,]),'value':([0,3,9,22,23,25,26,36,38,],[16,16,16,16,32,16,16,16,32,]),'appl':([0,3,9,22,23,25,26,36,38,],[4,4,4,4,4,4,4,4,4,]),'list_value':([3,9,25,],[18,21,33,]),'placeholder':([0,3,9,22,23,25,26,36,38,],[10,10,10,10,10,10,10,10,10,]),'annotation':([23,38,],[31,41,]),'empty':([0,3,9,22,23,25,26,36,38,],[6,6,6,6,6,6,6,6,6,]),'appl_value':([22,26,36,],[29,34,40,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> avalue','expr',1,'p_expr1','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',128),
  ('expr -> value','expr',1,'p_expr1','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',129),
  ('avalue -> value { annotation }','avalue',4,'p_avalue','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',135),
  ('value -> term','value',1,'p_value','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',139),
  ('value -> appl','value',1,'p_value','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',140),
  ('value -> list','value',1,'p_value','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',141),
  ('value -> tuple','value',1,'p_value','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',142),
  ('value -> string','value',1,'p_value','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',143),
  ('value -> placeholder','value',1,'p_value','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',144),
  ('value -> empty','value',1,'p_value','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',145),
  ('term -> DOUBLE','term',1,'p_term_double','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',151),
  ('term -> INT','term',1,'p_term_int','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',155),
  ('term -> NAME','term',1,'p_term_term','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',159),
  ('annotation -> value','annotation',1,'p_annotation1','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',167),
  ('annotation -> annotation , annotation','annotation',3,'p_annotation2','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',171),
  ('appl -> term ( appl_value )','appl',4,'p_appl','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',177),
  ('appl_value -> expr','appl_value',1,'p_appl_value1','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',181),
  ('appl_value -> appl_value , appl_value','appl_value',3,'p_appl_value2','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',185),
  ('list -> [ list_value ]','list',3,'p_list','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',191),
  ('list_value -> expr','list_value',1,'p_list_value1','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',195),
  ('list_value -> list_value , list_value','list_value',3,'p_list_value2','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',199),
  ('tuple -> ( list_value )','tuple',3,'p_tuple','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',205),
  ('tuple_value -> expr','tuple_value',1,'p_tuple_value1','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',209),
  ('tuple_value -> tuple_value , tuple_value','tuple_value',3,'p_tuple_value2','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',213),
  ('string -> STRING','string',1,'p_string','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',219),
  ('placeholder -> < PLACEHOLDER ( appl_value ) >','placeholder',6,'p_placeholder1','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',225),
  ('placeholder -> < PLACEHOLDER >','placeholder',3,'p_placeholder2','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',229),
  ('empty -> <empty>','empty',0,'p_empty','/home/stephen/continuum/blazepro/blaze/aterm/uaterm.py',235),
]
