
# D:\Develop\blaze\blaze\datashape\dyacc.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf6\xf1V-\xfak;>\xe9\t\x921\xa7\x93(_'
    
_lr_action_items = {'LBRACE':([0,2,3,5,6,7,8,9,11,19,20,21,24,25,26,28,30,39,41,44,45,46,47,],[1,-5,-11,-3,-12,-9,-8,-10,1,1,1,1,1,1,-24,-13,1,1,1,-22,1,-23,-4,]),'NAME':([0,1,2,3,5,6,7,8,9,10,11,19,20,21,22,23,24,25,26,27,28,30,38,39,41,44,45,46,47,],[3,18,-5,-11,-3,-12,-9,-8,-10,23,3,3,29,29,23,-7,3,3,-24,18,-13,3,23,3,3,-22,29,-23,-4,]),'SEMI':([1,3,6,7,8,9,13,14,17,26,27,28,40,42,44,46,51,],[-33,-11,-12,-9,-8,-10,27,-26,-27,-24,-33,-13,-32,27,-22,-23,-31,]),')':([3,6,7,8,9,26,28,29,31,32,33,34,35,36,37,43,44,46,48,49,50,],[-11,-12,-9,-8,-10,-24,-13,-17,-19,-15,-14,44,-18,-20,46,49,-22,-23,51,-16,-21,]),'(':([3,9,20,21,25,29,35,45,],[20,21,30,30,41,20,21,30,]),'NUMBER':([0,2,3,5,6,7,8,9,11,19,20,21,24,25,26,28,30,39,41,44,45,46,47,],[6,-5,-11,-3,-12,-9,-8,-10,6,6,31,31,6,6,-24,-13,6,6,6,-22,31,-23,-4,]),'EQUALS':([22,23,38,],[39,-7,-6,]),'STRING':([20,21,45,],[36,36,36,]),'COMMA':([2,3,6,7,8,9,26,28,29,31,32,33,34,35,36,37,40,43,44,46,47,48,49,50,],[19,-11,-12,-9,-8,-10,-24,19,-17,-19,-15,-14,45,-18,-20,45,19,19,-22,-23,19,19,-16,45,]),'COLON':([12,15,16,18,],[25,-29,-30,-28,]),'BIT':([0,1,2,3,5,6,7,8,9,11,19,20,21,24,25,26,27,28,30,39,41,44,45,46,47,],[9,15,-5,-11,-3,-12,-9,-8,-10,9,9,35,35,9,9,-24,15,-13,9,9,9,-22,35,-23,-4,]),'$end':([2,3,4,5,6,7,8,9,11,24,26,28,44,46,47,],[-5,-11,0,-3,-12,-9,-8,-10,-1,-2,-24,-13,-22,-23,-4,]),'TYPE':([0,1,2,3,5,6,7,8,9,11,24,26,27,28,44,46,47,],[10,16,-5,-11,-3,-12,-9,-8,-10,10,10,-24,16,-13,-22,-23,-4,]),'RBRACE':([1,3,6,7,8,9,13,14,17,26,27,28,40,42,44,46,51,],[-33,-11,-12,-9,-8,-10,26,-26,-27,-24,-33,-13,-32,-25,-22,-23,-31,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'rhs_expression':([0,11,19,24,25,30,39,41,],[2,2,28,2,40,43,47,48,]),'record_opt':([1,27,],[13,42,]),'top':([0,],[4,]),'stmt':([0,11,24,],[5,5,5,]),'record':([0,11,19,20,21,24,25,30,39,41,45,],[7,7,7,32,32,7,7,7,7,7,32,]),'appl':([0,11,19,20,21,24,25,30,39,41,45,],[8,8,8,33,33,8,8,8,8,8,33,]),'record_item':([1,27,],[14,14,]),'appl_args':([20,21,45,],[34,37,50,]),'record_name':([1,27,],[12,12,]),'lhs_expression':([10,22,38,],[22,38,38,]),'empty':([1,27,],[17,17,]),'mod':([0,11,24,],[11,24,24,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> top","S'",1,None,None,None),
  ('top -> mod','top',1,'p_top','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',175),
  ('mod -> mod mod','mod',2,'p_decl1','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',182),
  ('mod -> stmt','mod',1,'p_decl2','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',186),
  ('stmt -> TYPE lhs_expression EQUALS rhs_expression','stmt',4,'p_statement_assign','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',192),
  ('stmt -> rhs_expression','stmt',1,'p_statement_expr','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',210),
  ('lhs_expression -> lhs_expression lhs_expression','lhs_expression',2,'p_lhs_expression','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',216),
  ('lhs_expression -> NAME','lhs_expression',1,'p_lhs_expression_node','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',221),
  ('rhs_expression -> appl','rhs_expression',1,'p_rhs_expression_node1','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',227),
  ('rhs_expression -> record','rhs_expression',1,'p_rhs_expression_node1','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',228),
  ('rhs_expression -> BIT','rhs_expression',1,'p_rhs_expression_node2','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',232),
  ('rhs_expression -> NAME','rhs_expression',1,'p_rhs_expression_node3','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',236),
  ('rhs_expression -> NUMBER','rhs_expression',1,'p_rhs_expression_node3','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',237),
  ('rhs_expression -> rhs_expression COMMA rhs_expression','rhs_expression',3,'p_rhs_expression','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',241),
  ('appl_args -> appl','appl_args',1,'p_appl_args__appl__record','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',248),
  ('appl_args -> record','appl_args',1,'p_appl_args__appl__record','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',249),
  ('appl_args -> ( rhs_expression )','appl_args',3,'p_appl_args__rhs_expression','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',253),
  ('appl_args -> NAME','appl_args',1,'p_appl_args__name','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',257),
  ('appl_args -> BIT','appl_args',1,'p_appl_args__bit','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',261),
  ('appl_args -> NUMBER','appl_args',1,'p_appl_args__number','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',265),
  ('appl_args -> STRING','appl_args',1,'p_appl_args__string','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',269),
  ('appl_args -> appl_args COMMA appl_args','appl_args',3,'p_appl_args','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',273),
  ('appl -> NAME ( appl_args )','appl',4,'p_appl','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',280),
  ('appl -> BIT ( appl_args )','appl',4,'p_appl','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',281),
  ('record -> LBRACE record_opt RBRACE','record',3,'p_record','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',287),
  ('record_opt -> record_opt SEMI record_opt','record_opt',3,'p_record_opt1','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',291),
  ('record_opt -> record_item','record_opt',1,'p_record_opt2','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',295),
  ('record_opt -> empty','record_opt',1,'p_record_opt3','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',299),
  ('record_name -> NAME','record_name',1,'p_record_name','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',303),
  ('record_name -> BIT','record_name',1,'p_record_name','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',304),
  ('record_name -> TYPE','record_name',1,'p_record_name','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',305),
  ('record_item -> record_name COLON ( rhs_expression )','record_item',5,'p_record_item1','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',309),
  ('record_item -> record_name COLON rhs_expression','record_item',3,'p_record_item2','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',313),
  ('empty -> <empty>','empty',0,'p_empty','D:\\Develop\\blaze\\blaze\\datashape\\parser.py',319),
]
