#!/bin/bash
#
#
# This is the jenkins build script for building/testing
# Blaze.
#
# Jenkins Requirements:
#   - Anaconda should be installed in ~/anaconda
#   - Use a jenkins build matrix for multiple
#     platforms/python versions
#   - Use the XShell plugin to launch this script
#   - Call the script from the root workspace
#     directory as buildscripts/jenkins-build
#

# Require a version of Python to be selected
if [ "${PYTHON_VERSION}" == "" ]; then
 echo You must select a Python version with the PYTHON_VERSION variable.
 exit 1
fi

# Try to delete the build directory twice, with a pause in
# between, because on an OSX build machine this was failing
# on occasion.
rm -rf ${WORKSPACE}/build
sleep 1
rm -rf ${WORKSPACE}/build

if [ -d ${WORKSPACE}/build ]; then
 echo Failed to delete temporary build dir ${WORKSPACE}/build
 exit 1
fi

# Use conda to create a conda environment of the required
# python version and containing the dependencies.
# TODO: Re-add cffi to this list when it is in anaconda python 3.3
export PYENV_PREFIX=${WORKSPACE}/build/pyenv
~/anaconda/bin/conda create --yes --channel https://conda.binstar.org/mwiebe -p ${PYENV_PREFIX} python=${PYTHON_VERSION} cython=0.19 scipy ply dynd-python nose flask pyparsing pyyaml setuptools pip pytables multipledispatch || exit 1
export PATH=${PYENV_PREFIX}/bin:${PATH}

if [ -f "${PYENV_PREFIX}/bin/python" ]; then
 export PYTHON_EXECUTABLE=${PYENV_PREFIX}/bin/python
elif [ -f "${PYENV_PREFIX}/bin/python3" ]; then
 export PYTHON_EXECUTABLE=${PYENV_PREFIX}/bin/python3
else
 echo Conda environment creation failed.
 exit 1
fi

# Temporary hack to install datashape
rm -rf datashape
git clone https://github.com/ContinuumIO/datashape.git || exit 1
pushd datashape
${PYTHON_EXECUTABLE} setup.py install || exit 1
popd

# Temporary hack to install blz
# BLZ needs unittest2 for Python 2.6
if [ "${PYTHON_VERSION}" == "2.6" ]; then
  pip install unittest2
fi
rm -rf blz
git clone https://github.com/ContinuumIO/blz.git || exit 1
pushd blz
${PYTHON_EXECUTABLE} setup.py install || exit 1
popd


# Build/install Blaze
${PYTHON_EXECUTABLE} setup.py install || exit 1

# Run the tests (in a different directory, so the import works properly)
mkdir tmpdir
pushd tmpdir
${PYTHON_EXECUTABLE} -c 'import blaze;blaze.test(xunitfile="../test_results.xml", verbosity=2, exit=1)' || exit 1
popd
