package:
  name: blaze
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  entry_points:
    - blaze-server = blaze.server.spider:_main

source:
  git_url: https://github.com/blaze/blaze.git

requirements:
  build:
    - python
    - setuptools
    - contextlib2 # [py2k]
    - flask >=0.10.1
    - flask-cors
    - odo >=0.5.0
    - datashape >=0.5.3
    - psutil
    - sqlalchemy >=0.8.0
    - toolz
  run:
    - python
    - contextlib2 # [py2k]
    - cytoolz
    - flask >=0.10.1
    - flask-cors
    - h5py
    - numba
    - odo >=0.5.0
    - datashape >=0.5.3
    - psutil
    - pytables >=3.0.0
    - pyyaml
    - requests
    - sqlalchemy >=0.8.0

test:
  imports:
    - blaze
  requires:
    - pytest >=2.7.0
    - psycopg2 # [unix]
    - pymongo >=3.0 # [unix]
    - bcolz   # [unix]
    - pymysql
    - sqlite
  commands:
    - py.test -vx --doctest-modules --doctest-ignore-import-errors --pyargs blaze -rsxX

about:
  home: http://blaze.pydata.org
  license: BSD
